services:
  da3:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: da3_ros2:v2
    container_name: da3
    hostname: orbslam3
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - TZ=Asia/Hong_Kong
      - ROS_HOSTNAME=orbslam3
      - ROS_MASTER_URI=http://orbslam3:11311
      - DISPLAY=:2
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - $HOME/.cache/huggingface:/root/.cache/huggingface:rw
      - $HOME/.cache/clip:/root/.cache/clip:rw
    command: bash /init.sh
    tty: true
    stdin_open: true
